site_name: "TorchXAI"
site_description: Explainable AI library for PyTorch
site_url: "https://atriaml.github.io/torchxai/"
site_author: "Saifullah Saifullah"
dev_addr: "127.0.0.1:8080"
repo_url: https://github.com/atriaml/torchxai
theme:
  name: shadcn
  icon: null
  topbar_sections: false
  pygments_style:
    light: shadcn-light
    dark: github-dark
  katex_options:
    trust: true
    macros:
      "\\dx": "\\mathrm{d}x"
      "\\NN": "\\mathbb{N}"
  # show_datetime: true
  accent: "oklch(63% 0.24 25)"

plugins:
  - search
  - excalidraw
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      locale: en
      handlers:
        python:
          options:
              docstring_options:
              docstring_style: google
              ignore_init_summary: true
              docstring_section_style: list
              relative_crossrefs: true
              scoped_crossrefs: true
              signature_crossrefs: true
              unwrap_annotated: true
              filters: public
              inherited_members: true
              summary: true
              heading_level: 1
              parameter_headings: true
              type_parameter_headings: true
              show_root_heading: true
              show_root_full_path: false
              show_symbol_type_heading: true
              show_symbol_type_toc: true
              line_length: 88
              merge_init_into_class: false
              separate_signature: true
              show_signature_annotations: true
              show_signature_type_parameters: true
              backlinks: tree
              show_bases: false
              show_inheritance_diagram: false
              show_source: true
  - autonumber:
      prefixes:
        th: Theorem

markdown_extensions:
  admonition:
  codehilite:
  fenced_code:
  footnotes:
  extra:
  pymdownx.blocks.details:
  pymdownx.tabbed:
  pymdownx.blocks.tab:
    combine_header_slug: true
    separator: ___
  pymdownx.progressbar:
  pymdownx.snippets:
  pymdownx.arithmatex:
    generic: true
  shadcn.extensions.echarts.alpha:
  shadcn.extensions.codexec:
  shadcn.extensions.iconify:
  pymdownx.blocks.caption:
  shadcn.extensions.hover_card:


nav:
  - Getting Started:
    - index.md
    - install.md
    - usage.md
  - Explainers:
    - Overview: explainers.md
    - Base Explainer: explainers/base_explainer.md
    - Gradient Methods:
      - explainers/saliency.md
      - explainers/input_x_gradient.md
      - explainers/input_x_baseline_gradient.md
      - explainers/guided_backprop.md
      - explainers/deeplift.md
      - explainers/deeplift_shap.md
      - explainers/integrated_gradients.md
      - explainers/gradient_shap.md
    - Perturbation Methods:
      - explainers/feature_ablation.md
      - explainers/occlusion.md
      - explainers/lime.md
      - explainers/kernel_shap.md
    - Baseline Methods:
      - explainers/random.md
    - Examples:
      - explainers/examples/image_classification.md
      - explainers/examples/sequence_classification.md
      - explainers/examples/token_classification.md
  - Metrics:
    - Overview: metrics.md
    - Axiomatic:
      - metrics/completeness.md
      - metrics/input_invariance.md
      - metrics/non_sensitivity.md
    - Faithfulness:
      - metrics/aopc.md
      - metrics/abpc.md
      - metrics/faithfulness_corr.md
      - metrics/faithfulness_estimate.md
      - metrics/infidelity.md
      - metrics/monotonicity.md
      - metrics/monotonicity_corr.md
      - metrics/sensitivity_n.md
    - Complexity:
      - metrics/complexity_entropy.md
      - metrics/complexity_sundararajan.md
      - metrics/effective_complexity.md
      - metrics/sparseness.md
    - Robustness:
      - metrics/sensitivity_max.md
      - metrics/sensitivity_avg.md
    - Diagnosis:
      - metrics/attribution_localization.md
      - metrics/attribution_locality.md
      - metrics/modality_topk_fraction.md
      - metrics/attribution_text_analysis.md